/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Berk Gedik (https://sketchfab.com/berkgedik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/funko-test-model-4bbdf45266664005bdc94416041191d2
title: Funko Test Model
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/funko_test_model/funko.gltf");
  return (
    <group {...props} dispose={null} scale={0.005}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-5.12, 260.36, 1.1]}
            rotation={[-1.55, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials.Body}
            />
          </group>
          <group
            position={[-4.75, 214.62, 76.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.Body}
            />
          </group>
          <group
            position={[-4.69, 267.92, 95.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-4.69, 266.9, 95.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-5.12, 260.36, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-5.12, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-5.12, 101.61, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-5.12, 101.61, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.Others}
            />
          </group>
          <group
            position={[-5.12, 101.61, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.Body}
            />
          </group>
          <group
            position={[-5.12, 260.36, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.Body}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/funko_test_model/funko.gltf");
