/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Maxim Mavrichev (https://sketchfab.com/mvrc.art)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vr-gallery-1ac32ed62fdf424498acc146fad31f7e
title: VR Gallery
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/vr_gallery/world.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.VR_Gallery_Baked_0.geometry}
              material={materials.Baked}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/vr_gallery/world.gltf");
